### ISSUE TITLE
Output is not matching

### ISSUE THREAD

**Issue by ankushdharkar** [strider99/node-practice#1]
![image](https://user-images.githubusercontent.com/1935403/33976964-648db516-e0be-11e7-80e7-572a2c4b9b16.png)

**Comment by strider99** [comment]
I was unable to replicate the bug. I cleaned up the formatting of the output a bit. When you are free, can you check and tell me whether it works now.
![image](https://user-images.githubusercontent.com/7549876/33982481-b3d6be70-e0d6-11e7-91b8-8bf3cb11aebf.png)
![image](https://user-images.githubusercontent.com/7549876/33982499-c60fb02e-e0d6-11e7-9029-58665a29d7ec.png)
Lets keep the issue open till you check again.

**Comment by ankushdharkar** [comment]
So strange. I checked your code. You're right. This should not be happening. But it is, even with the new code

<img width="600" alt="screen shot 2017-12-17 at 6 10 50 am" src="https://user-images.githubusercontent.com/1935403/34075585-2bba4ea4-e2f1-11e7-87a3-4aa893151c09.png">

I wonder if it has something to do with how this line is handled [here](https://github.com/strider99/node-practice/blob/c510daa45c93d55627a10b15bb5882f1afe38322/util/Read-CSV.js#L16)

**Comment by strider99** [comment]
fixed. now it will work. now uses regex for splitting.
